#%Dialect 1.0

dialect: DB Config
version: 1.1

uses:
  infra: ../vocabulary/infra.yaml
  cfg: ../vocabulary/config.yaml

external:
  schema-org: http://schema.org/
  dbconfig: http://mycompany.com/dialects/dbconfig#

nodeMappings:

  DatabaseConfigNode:
    classTerm: cfg.ConfigurationItem
    mapping:
      server:
        propertyTerm: cfg.configured
        range: DatabaseServerNode
      dbs:
        propertyTerm: dbconfig.dbs
        mapKey: cfg.environment
        range: DatabaseNode

  DatabaseNode:
    classTerm: infra.Database
    mapping:
      environment:
        propertyTerm: cfg.environment
        range: string
        enum:
          - development
          - production
          - testing
          - qa
      name:
        propertyTerm: schema-org.name
        range: string
        mandatory: true
      username:
        propertyTerm: cfg.username
        range: string

  DatabaseServerNode:
    classTerm: infra.DatabaseServer
    mapping:
      host:
        mandatory: true
        propertyTerm: infra.endpoint
        range: string
      port:
        mandatory: true
        propertyTerm: infra.port
        range: integer
      driver:
        mandatory: true
        propertyTerm: infra.driver
        range: string

documents:
  root:
    encodes: DatabaseConfigNode
  fragments:
    encodes:
      DatabaseServer: DatabaseServerNode
