#%Vocabulary 1.0

vocabulary: Configuration

base: http://mycompany.com/vocabularies/config#

classTerms:

  ConfigurationItem:
    description: Set of properties configuring an element

propertyTerms:

  configured:
    description: Any element that is being configured

  environment:
    description: Configuration environment

  username:
    description: identifier for a user account
